services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins_network

  #nginx:
  #  image: nginx:latest
  #  container_name: nginx-jenkins
  #   ports:
  #     - "445:443"
  #     - "81:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/certs:/etc/nginx/ssl:ro
  #   depends_on:
  #     - jenkins
  #   networks:
  #     - jenkins_network



networks:
  jenkins_network: